# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDede():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_dede(self):
    self.driver.get("http://127.0.0.1/registro.html")
    self.driver.set_window_size(1382, 744)
    self.driver.find_element(By.ID, "Password").click()
    self.driver.find_element(By.ID, "Usuario").click()
    self.driver.find_element(By.ID, "Usuario").send_keys("laurac@hotmail.com")
    self.driver.find_element(By.ID, "Password").click()
    self.driver.find_element(By.ID, "Password").send_keys("0620Parte")
    self.driver.find_element(By.ID, "Name").click()
    self.driver.find_element(By.ID, "Name").send_keys("laura")
    self.driver.find_element(By.ID, "Apellido").click()
    time.sleep(1)
    self.driver.find_element(By.ID, "Apellido").send_keys("mendonca")
    self.driver.find_element(By.ID, "dni").click()
    self.driver.find_element(By.ID, "dni").send_keys("24567890")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(11) > #Password").click()
    time.sleep(1)
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(11) > #Password").send_keys("20/06/1998")
    self.driver.find_element(By.ID, "femenino").click()
    self.driver.find_element(By.ID, "Pais").click()
    self.driver.find_element(By.ID, "Pais").send_keys("Argentina")
    self.driver.find_element(By.NAME, "Submit").click()
  


test = TestDede()
test.setup_method(None)
test.test_dede()
time.sleep(5)
test.teardown_method(None)